---

# restarts the ssh service only if conf file was change
- name: Restart samba daemon
  ansible.builtin.service:
    name: smbd.service
    state: restarted
  listen: "restart share services"

- name: Restart nmbd daemon
  ansible.builtin.service:
    name: nmbd.service
    state: restarted
  listen: "restart share services"
