---

# system role vars
username: jbukuts
hostname: jakes-server
packages:
  - vim
  - htop
  - neofetch
  - speedtest-cli
  - build-essential
  - net-tools
  - smartmontools

# setup for pulling .ovpn files to server
ovpn_file_name: 'dropbucket-india.ovpn'
ovpn_remote_path: '/home/dropbucket/{{ ovpn_file_name }}'
ovpn_dest_path: '/home/{{ username }}/vpn_files/'

force_docker_containers_restart: false

# mdadm role vars
# arrays:
#   - name: md0
#     state: absent
#     filesystem: ext4
#     level: 1
#     devices:
#       - '/dev/sda'
#       - '/dev/sdb'

# zfs role vars
pools:
  - name: md0
    state: present
    level: mirror
    devices:
      - '/dev/disk/by-id/ata-WL3000GSA6472E_WD-WMC130D0KPVL'
      - '/dev/disk/by-id/ata-WL3000GSA6472E_WD-WMC130E02HUT'

# samba role vars
shares:
  - name: "safe_share"
    state: present
    path: '/mnt/md0'

# geerlingguy role vars
docker_users:
  - "{{ username }}"

pip_install_packages:
  - name: docker

# docker_apt_gpg_key: "https://download.docker.com/linux/ubuntu/gpg"
# docker_apt_repository: "deb https://download.docker.com/linux/ubuntu jammy stable"
