---

# create groups using a loop
- name: Ensure all necessary groups are created
  group:
    name: "{{ item }}"
  loop:
    - docker
    - samba
    - "{{ username }}"

# allow our user sudo privilege with no password
- name: Enable passwordless sudo "{{ username }}"
  lineinfile:
    dest: /etc/sudoers
    regexp: "^%wheel"
    line: "{{ username }} ALL=(ALL) NOPASSWD: ALL"
    validate: "/usr/sbin/visudo -cf %s"

# suppress the login message
- name: Suppress login message
  file:
    path: "/home/{{ username }}/.hushlogin"
    mode: 0644
    owner: "{{ username }}"
    group: "{{ username }}"
    modification_time: preserve
    access_time: preserve
    state: touch