---

# prune items
- name: Prune containers, images, and volumes
  community.docker.docker_prune:
    images: true
    images_filters:
      dangling: true
    containers: true
    volumes: true
    builder_cache: true
